# Site settings
title: Blockologist
email: leigh765@me.com
description: "Blockologist is a time managementn tool which integrates JIRA or Trello with your Google calendar."
twitter_username: blockologist

baseurl : ''
url: http://ineedyourbrain.github.io/blockologist/
#url: http://localhost:4000/
# Build settings
markdown: kramdown
permalink: pretty
